### PR TITLE
Fix svn history for files which were in a renamed directory

### LINKED ISSUE #3443: Subversion history is incomplete when a folder has been renamed
**Describe the bug**
For a subversion repository where a folder has been renamed and then a file within that folder has subsequently been amended, the cached history created by the indexer is incomplete. This is similar to #761.
If the cached history is deleted or somehow ignored then the history gathered via SubversionHistoryParser for the single file is correct.

This is reproducible in the latest version of OpenGrok.

**To Reproduce**
This can be seen by replacing the existing svnlog.dump file in the testdata with the one attached which has 4 additional commits.
[svnlog.zip](https://github.com/oracle/opengrok/files/6068435/svnlog.zip)

Using a test over the subversion repository in FileHistoryCacheTest you can then verify the history of the file which should have 3 history entries:
```
        File testFileInRenamedFolder = new File(reposRoot.toString() +
          File.separatorChar + "renamedFolder" + File.separatorChar +  "FileInRenamedFolder.txt");
        History cachedHistory = cache.get(testFileInRenamedFolder, repo, false);
        History fullHistory = repo.getHistory(testFileInRenamedFolder);
        assertEquals(fullHistory.getHistoryEntries(), cachedHistory.getHistoryEntries());
```

**Expected behavior**
The history produced by the initial indexing of a subversion repository should contain the complete history for a file which is in a folder which has been renamed.
The correct history in this case can be seen by bypassing the cache (as shown in the test snippet), which would be achieved if the initial repository History was able to correctly identify the file as _renamed_

**Additional context**
The subversion history contains renames of folders in the following format:
```
<path
   text-mods="false"
   kind="dir"
   copyfrom-path="/repo/originalfoldername/src"
   copyfrom-rev="564779"
   action="A"
   prop-mods="false">/repo/newfoldername/src</path>
```

I don't think that there is an easy way to determine the contents of the folder at the point of discovering such a directive, and therefore it doesn't seem immediately obvious that this could be turned into a list of _renamedFiles_ by the history parser.
The approach that I have considered would be to simply extend History to track renamed directories as well. Then History.isRenamed could check both the file and the directory. 
The downside here is that this will catch too many files causing any file in a directory that was ever renamed as a renamed file, this may lead to some performance degredation of initial indexing. For extreme cases where much of the repository has been renamed it might even lead to the consumption of the complete history being largely redundant and instead an alternate approach of simply generating the history for each file independently being prefered. Possibly some overlap with comments on #3243 about chunking the history consumption.

### PR DESCRIPTION
**Pull request by harrisric**
Fixes #3443

### CODE REVIEW

File: opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java [hunk 1]
```diff
@@ -282,6 +291,73 @@
...
+    private Executor getDirectoryListExecutor(final String dir, String atRevision, CommandTimeoutType cmdType) {
+
+        List<String> cmd = new ArrayList<>();
+        ensureCommand(CMD_PROPERTY_KEY, CMD_FALLBACK);
+        cmd.add(RepoCommand);
+        cmd.add("ls");
+        cmd.add(escapeFileName(dir));
+        cmd.add("-r" + atRevision);
+
+        return new Executor(cmd, new File(getDirectoryName()),
```
[the remark this answers is not in the document]
Comment (harrisric) [reply opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java:312]: Using the same pattern as L135, L257 and L509.

**Comment by vladak** [comment]
Have you signed OCA before ? If not, please start the OCA process so the PR can be merged in.

**Comment by harrisric** [comment]
@vladak my company [alfa  ](https://github.com/alfasoftware) has just signed the OCA.

**Comment by vladak** [comment]
> @vladak my company [Alfa ](https://github.com/alfasoftware) has just signed the OCA.

Cool. One more thing is needed:
1. Contact us and we will add you to the list of contributors for the existing agreement.
Send an email to [opensource_ww_grp@oracle.com ](mailto:opensource_ww_grp@oracle.com) including your first name, last name, email, GitHub username (optional) and GitHub project/s that you would intend to contribute to.
2. After you are added to the list of members, go back the the homepage and check the list of signatories from the top menu, your name should be displayed on the list.

**Comment by harrisric** [comment]
@vladak should all be done now thanks.

File: opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java [hunk 2]
```diff
@@ -87,19 +94,31 @@ private static class Handler extends DefaultHandler2 {
...
+            isRenamedFile = false;
+            isRenamedDir = false;
             if ("logentry".equals(qname)) {
                 entry = new HistoryEntry();
                 entry.setActive(true);
                 entry.setRevision(attr.getValue("revision"));
             } else if ("path".equals(qname)) {
-                isRenamed = attr.getIndex("copyfrom-path") != -1;
+                if (attr.getIndex(COPYFROM_PATH) != -1) {
+                  LOGGER.info("rename for:" + attr.getValue(COPYFROM_PATH) );
```
Comment (vladak) [inline opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java:115]: could you reduce the level to e.g. `FINE` ? This would be too noisy in the logs, I think.

**Comment by vladak** [comment]
> @vladak should all be done now thanks.

Cool. Besides the logging nit this is good to go.

File: opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java (hunk 2 above)
Comment (vladak) [reply opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java:115]: actually, I will fix it after that fact.

**Comment by vladak** [comment]
Thanks !
