### PR TITLE
Search result background color for odd rows fix

### LINKED ISSUE #2082: background color of highlighted documents in search result change inconsistently
Issue can be seen on the screenshot:

screen shot 2018-04-24 at 10 41 54

It just seems weird to me that the color changes only when multiple documents are found in the same directory. I think it would be better if the color would change for every row or the same color would be at the start of the directory.

### PR DESCRIPTION
**Pull request by Orviss**
fixes #2082

I was not able to resolve this by css :(

Thanks for review :) 

For comparison: (almost the same part as described in issue)
screen shot 2018-04-25 at 17 07 44

### CODE REVIEW

**Comment by vladak** [comment]
Looks good enough to me.

File: src/org/opensolaris/opengrok/search/Results.java [hunk 1]
```diff
@@ -253,6 +247,20 @@ public static void prettyPrint(Writer out, SearchHelper sh, int start,
                 out.write("</tt></td></tr>\n");
             }
         }
+        out.write("</tbody>");
```
Comment (tarzanek) [inline src/org/opensolaris/opengrok/search/Results.java]: really?
(I am just confused it wasn't there before ... isn't it close somewhere else? )

Comment (Orviss) [reply src/org/opensolaris/opengrok/search/Results.java]: I was surprised as well. It seems the browser adds it there by itself.

Simple test: (when I `Inspect Element` the `<tbody>` is there)
```html
<!doctype html>
<html>
<head>
</head>
<body>
	<table>
		<tr><td>test1</td></td>
		<tr><td>test2</td></td>
	</table>
</body>
</html>
```

**Comment by tarzanek** [comment]
thank you, closing
